#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / "README.md"

CATEGORIES = [
    "classification-routing.md",
    "verification-guardrails.md",
    "scoring-ranking.md",
    "agent-decisions.md",
    "data-labeling-curation.md",
    "evaluation-benchmarking.md",
    "calibration-research.md",
    "infra-sdks-integrations.md",
    "game-simulation.md",
    "compliance-legal.md",
    "content-moderation.md",
    "related-practices-discussions.md",
]

OPEN_TRACKING = [
    "scientific-pipelines.md",
]

ALL_FILES = CATEGORIES + OPEN_TRACKING


class Category:
    def __init__(self, filename: str, title: str, count: int, lines: list[str]) -> None:
        self.filename = filename
        self.title = title
        self.count = count
        self.lines = lines

    @property
    def path(self) -> str:
        return f"categories/{self.filename}"


def github_anchor(title: str) -> str:
    anchor = title.strip().lower()
    anchor = re.sub(r"[^a-z0-9\- /]", "", anchor)
    anchor = anchor.replace("/", "-")
    anchor = re.sub(r"\s+", "-", anchor)
    anchor = re.sub(r"-+", "-", anchor)
    return anchor.strip("-")


def pluralize(count: int) -> str:
    return "entry" if count == 1 else "entries"


def parse_category(filename: str) -> Category:
    path = REPO_ROOT / "categories" / filename
    lines = path.read_text().splitlines()

    try:
        title = next(line[2:].strip() for line in lines if line.startswith("# "))
    except StopIteration as exc:
        raise ValueError(f"missing title in {path}") from exc

    try:
        entries_index = lines.index("## Entries")
    except ValueError as exc:
        raise ValueError(f"missing '## Entries' section in {path}") from exc

    raw_entry_lines = lines[entries_index + 1 :]
    while raw_entry_lines and not raw_entry_lines[0].strip():
        raw_entry_lines.pop(0)
    while raw_entry_lines and not raw_entry_lines[-1].strip():
        raw_entry_lines.pop()

    count = sum(1 for line in raw_entry_lines if line.startswith("- ["))

    rendered: list[str] = []
    previous_blank = False
    for line in raw_entry_lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("<!--"):
            if rendered and not previous_blank:
                rendered.append("")
                previous_blank = True
            continue
        if line.startswith("### ") or line.startswith("- ["):
            rendered.append(line)
            previous_blank = False

    while rendered and not rendered[-1].strip():
        rendered.pop()

    if count == 0:
        rendered = ["_No direct Jev examples added yet._"]

    return Category(filename=filename, title=title, count=count, lines=rendered)


def bullet_line(category: Category) -> str:
    return f"- [{category.title}]({category.path}) — {category.count} {pluralize(category.count)}"


def full_section(category: Category) -> list[str]:
    lines = [f"### {category.title}", "", f"Source file: [`{category.path}`]({category.path})", ""]
    lines.extend(category.lines)
    lines.append("")
    return lines


def check_duplicates(categories: dict[str, Category]) -> list[tuple[str, list[str]]]:
    """Find entries whose primary source URL appears in more than one category."""
    url_map: dict[str, list[str]] = {}
    for category in categories.values():
        for line in category.lines:
            if not line.startswith("- ["):
                continue
            m = re.search(r"\((https?://[^)\s]+)\)", line)
            if m:
                key = m.group(1).lower().rstrip("/")
                url_map.setdefault(key, []).append(category.filename)
    return [(url, files) for url, files in url_map.items() if len(files) > 1]


def build_readme() -> str:
    categories = {filename: parse_category(filename) for filename in ALL_FILES}

    open_categories = [categories[name] for name in OPEN_TRACKING]

    # ---------- duplicate detection ----------
    duplicates = check_duplicates(categories)
    if duplicates:
        print("⚠️  WARNING: duplicate sources detected:")
        for url, files in duplicates:
            print(f"    {url} appears in {', '.join(files)}")
        print()

    # ---------- build ----------
    non_empty = [
        category
        for category in categories.values()
        if category.count > 0 and category.filename not in OPEN_TRACKING
    ]

    out: list[str] = [
        "# awesome-jev",
        "",
        "<!-- Generated by scripts/build-readme.py. Edit category files, then rebuild README. -->",
        "",
        "A curated awesome list of public projects and practices built on [Jev](https://typesafe.ai/blog/introducing-system-one-models-and-jev), TypeSafe AI's System One model for typed decisions.",
        "",
        "This README is the homepage aggregate of the current category files, so the latest accepted entries are visible here without drilling into subpages.",
        "",
        "Jev is not a chat model. It takes unstructured state plus a **typed question** and returns a **typed decision** — a choice, a score, or a boolean, each with a confidence. That makes it a drop-in decision layer for software: classification, routing, rubric scoring, verification, and agent guardrails. This list tracks who is actually building with it, and which patterns transfer across industries.",
        "",
        "The repository treats all categories equally — each entry lives in exactly one category, chosen by its direct Jev application domain. A dedicated **Related Practices / Discussions** category captures credible public practice signals — X threads, Reddit discussions, and interviews — that describe real Jev usage even when no strong standalone case page exists yet.",
        "",
        "## Why this list",
        "",
        "Most Jev discussion is scattered across launch threads, model-gateway listings, and one-off prototypes. This list answers two practical questions quickly:",
        "",
        "- Where is Jev already making real decisions in production workflows?",
        "- Which decision patterns transfer across industries?",
        "",
        "This is not a comprehensive database. It is a high-signal, fast-scanning field guide.",
        "",
        "## Inclusion criteria",
        "",
        "An entry should meet all of the following:",
        "",
        "- The source is public and citable.",
        "- The example **uses Jev** (or a documented Jev port/derivative) for a concrete decision task — not a generic classifier, router, or LLM judge with no Jev involvement.",
        "- The source explicitly names `Jev`/`jev`, cites TypeSafe AI's System One models, or shows a typed-decision loop (typed question → typed answer with confidence → accept/reject/escalate).",
        "- The summary explains the scenario, method, and value in one sentence.",
        "",
        "We do **not** include:",
        "",
        "- Generic classifiers, routers, or research agents that merely resemble the pattern without using Jev.",
        "- Pure theory or opinion without a concrete practice.",
        "- Launch-hype commentary with no working artifact or reproducible result.",
        "- Long write-ups inside the list itself.",
        "- Sources that are private, inaccessible, or too vague to classify.",
        "",
        "## Current coverage",
        "",
    ]

    out.extend(
        bullet_line(category) for category in categories.values() if category.filename not in OPEN_TRACKING
    )
    out.extend(
        [
            "",
            "### Open categories still being seeded",
            "",
        ]
    )
    out.extend(bullet_line(category) for category in open_categories)
    out.extend(
        [
            "",
            "Each entry lives in exactly one category. When a project could fit multiple categories, we choose the one closest to its direct application domain.",
            "",
            "## Browse by category",
            "",
        ]
    )

    for category in non_empty:
        out.append(f"- [{category.title}](#{github_anchor(category.title)}) ([source]({category.path}))")

    out.extend(
        [
            "",
            "## Full list",
            "",
        ]
    )

    for category in non_empty:
        out.extend(full_section(category))

    out.extend(
        [
            "## Submission format",
            "",
            "Use exactly one line per entry:",
            "",
            "```md",
            "- [Name](URL) - Industry: one-sentence description of the Jev use case.",
            "```",
            "",
            "## How to contribute",
            "",
            "1. Pick the category that best matches the direct Jev application domain.",
            "2. Add a single-line entry in the required format to the category file, not directly to the README aggregate.",
            "3. Keep the summary concrete and scannable.",
            "4. Prefer examples that clearly show scenario + typed decision + value.",
            "",
            "See [CONTRIBUTING.md](CONTRIBUTING.md) for details.",
            "",
            "## License",
            "",
            "MIT",
            "",
        ]
    )

    return "\n".join(out)


def main() -> None:
    README_PATH.write_text(build_readme())


if __name__ == "__main__":
    main()
